name: Jaggi First Workflow

on: [push]

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print message
        run: echo "Hello Jaggi! GitHub Actions is working 💥"
